app/routes/admin.py
from werkzeug.utils import secure_filename
from flask import Blueprint, render_template, url_for, session, redirect, request, flash, send_from_directory
from app.models.models import Product, User, Order
from app import db

admin = Blueprint('admin', __name__)


@admin.route('/media/<path:filename>')
def get_image(filename):
    return send_from_directory('../media', filename)


@admin.route('/add-product', methods=['GET', 'POST'])
def add_product():
    if session['user_id'] == 1:
        if request.method == 'POST':
            product_name = request.form.get('product-name')
            mrp = float(request.form.get('mrp'))
            discount_price = float(request.form.get('discount-price'))
            discount_percent = int(request.form.get('discount-percent'))
            in_stock = int(request.form.get('in-stock-amt'))

            file = request.files.get('product-image')
            file_name = secure_filename(file.filename)

            file_path = f'./media/{file_name}'
            file.save(file_path)

            new_product = Product(product_name=product_name, discounted_price=discount_price, mrp=mrp, in_stock=in_stock,
                                  product_image=file_path, discount_percentage=discount_percent)
            db.session.add(new_product)
            db.session.commit()
            flash(f'{product_name} added!', 'success')
        return render_template('add-product.html')

    return render_template('404.html')


@admin.route('/shop-products', methods=['GET', 'POST'])
def shop_products():
    if session['user_id'] == 1:
        products = Product.query.order_by('date_added').all()
        return render_template('shop-products.html', products=products)

    return render_template('404.html')


@admin.route('/update-product/<int:product_id>', methods=['GET', 'POST'])
def update_product(product_id):
    if session['user_id'] == 1:
        product = Product.query.filter_by(id=product_id).first()
        if product:
            if request.method == 'POST':
                product_name = request.form.get('product-name')
                mrp = float(request.form.get('mrp'))
                discount_price = float(request.form.get('discount-price'))
                discount_percent = int(request.form.get('discount-percent'))
                in_stock = int(request.form.get('in-stock-amt'))

                file = request.files.get('product-image')
                file_name = secure_filename(file.filename)

                file_path = f'./media/{file_name}'
                file.save(file_path)

                try:
                    product.product_name = product_name
                    product.mrp = mrp
                    product.discounted_price = discount_price
                    product.discount_percentage = discount_percent
                    product.in_stock = in_stock
                    product.product_image = file_path

                    db.session.commit()
                    flash(f'{product_name} updated successfully', 'success')
                    return redirect(url_for('admin.shop-products'))

                except Exception as ex:
                    flash(f'Item not updated', 'danger')

            return render_template('update-product.html', product=product)

    return render_template('404.html')


@admin.route('/delete-product/<int:product_id>', methods=['GET', 'POST'])
def delete_product(product_id):
    if session['user_id'] == 1:
        product = Product.query.filter_by(id=product_id).first()
        db.session.delete(product)
        db.session.commit()
        flash(f'{product.product_name} deleted', 'success')
        return redirect(url_for('admin.shop-products'))

    return render_template('404.html')


@admin.route('/app-users')
def app_users():
    if session['user_id'] == 1:
        users = User.query.order_by('date_joined')
        return render_template('users.html', users=users)
    return render_template('404.html')


@admin.route('/admin-panel')
def admin_panel():
    if session['user_id'] == 1:
        return render_template('admin.html')
    return render_template('404.html')


@admin.route('/view-orders')
def view_orders():
    if session['user_id'] == 1:
        orders = Order.query.all()
        return render_template('view-orders.html', orders=orders)

    return render_template('404.html')


@admin.route('/update-status/<int:order_id>', methods=['GET', 'POST'])
def update_status(order_id):
    if session['user_id'] == 1:
        order = Order.query.filter_by(id=order_id).first()
        if request.method == 'POST':
            status = request.form.get('status')
            order.status = status
            db.session.commit()
            flash('Order Status Updated.', 'success')
            return redirect(url_for('admin.view_orders'))
        return render_template('update-order-status.html', order=order)

    return render_template('404.html')

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash
from app import bcrypt, db
from app.models.models import User

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user and bcrypt.check_password_hash(user.password, password):
            session['user_id'] = user.id
            flash("Logged In", 'success')
            return redirect(url_for('main.home'))
        elif not user:
            flash("Email does not exist", 'success')
            return redirect(url_for('auth.register'))
        else:
            flash('Password is incorrect', 'success')
    return render_template('login.html')


@auth.route('/sign-up', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm-password')

        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email already exists. Try with different email', 'danger')
        else:
            if password == confirm_password:
                hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
                new_user = User(username=username, email=email, password=hashed_password)
                db.session.add(new_user)
                db.session.commit()
                flash('Account Successfully Created', 'success')
                return redirect(url_for('auth.login'))
            else:
                flash('Password does not match', 'danger')

    return render_template('register.html')


@auth.route('/logout')
def logout():
    session.pop('user_id', None)
    flash('Logged out', 'success')

    return redirect(url_for('auth.login'))


@auth.route('/profile/<int:user_id>')
def profile(user_id):
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))
    user = User.query.filter_by(id=session['user_id']).first()
    return render_template('profile.html', user=user)


@auth.route('/change-password', methods=['POST'])
def change_password():
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))
    user = User.query.filter_by(id=session['user_id']).first()
    if user:
        current_password = request.form.get('old-password')
        new_password = request.form.get('new-password')
        confirm_new_password = request.form.get('confirm-new-password')

        if new_password != confirm_new_password:
            flash('The passwords doesnot match!', 'danger')
        elif bcrypt.check_password_hash(user.password, current_password) and new_password == confirm_new_password:
            new_hashed_password = bcrypt.generate_password_hash(password=new_password)
            user.password = new_hashed_password
            db.session.commit()
            flash('Your password has been updated!', 'success')
    return redirect(url_for('auth.profile', user_id=user.id))

app/routes/main.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from app.models.models import User, Product, Cart, Order
from app import db

main = Blueprint('main', __name__)


@main.route('/')
def home():
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))
    user = User.query.filter_by(id=session['user_id']).first()
    products = Product.query.all()
    return render_template('home.html', user=user, products=products,
                           cart=Cart.query.filter_by(user_link=session['user_id']).all())


@main.route('/cart')
def view_cart():
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))
    cart = Cart.query.filter_by(user_link=session['user_id']).all()
    total_amount = 0
    for item in cart:
        amount = item.product.discounted_price * item.quantity
        total_amount += amount

    return render_template("cart.html", cart=cart, total_amount=total_amount)


@main.route('/add-to-cart/<int:product_id>', methods=['GET', 'POST'])
def add_to_cart(product_id):
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))

    cart_exists = Cart.query.filter_by(product_link=product_id, user_link=session['user_id']).first()
    if cart_exists:
        cart_exists.quantity += 1
        db.session.commit()
        flash('Item incremented successfully', 'success')
    else:
        cart = Cart(quantity=1, user_link=session['user_id'], product_link=product_id)
        db.session.add(cart)
        db.session.commit()
        flash('Item added to cart', 'success')
    return redirect(url_for('main.view_cart'))


@main.route('/remove-cart-product/<int:cart_id>', methods=['POST'])
def remove_cart_product(cart_id):
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))

    cart = Cart.query.filter_by(id=cart_id).first()
    db.session.delete(cart)
    db.session.commit()
    flash('Item removed from the cart.')
    return redirect(url_for('main.view_cart'))


@main.route('/checkout', methods=['GET', 'POST'])
def checkout():
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))

    user = User.query.filter_by(id=session['user_id']).first()
    cart = Cart.query.filter_by(user_link=user.id).all()

    if request.method == 'POST':
        first_name = request.form.get('first-name')
        last_name = request.form.get('last-name')
        address = request.form.get('address')
        city = request.form.get('city')
        state = request.form.get('state')
        pin_code = request.form.get('pin')
        phone = request.form.get('phone')

    total_amount = 0
    for item in cart:
        amount = item.product.discounted_price * item.quantity
        total_amount += amount

    return render_template('checkout.html', user=user, cart=cart, total_amount=total_amount)


@main.route('/order_confirmed')
def order_confirm():
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))
    else:
        cart = Cart.query.filter_by(user_link=session['user_id']).all()
        if len(cart) < 1:
            flash('Your cart is empty.', 'danger')
        else:
            for item in cart:
                product = Product.query.get(item.product_link)
                new_order = Order(quantity=item.quantity, user_link=session['user_id'], product_link=product.id,
                                  price=item.quantity * product.discounted_price, payment_id=1)
                db.session.add(new_order)
                db.session.delete(item)
            db.session.commit()

            flash('Your order has been placed', 'success')
    return redirect(url_for('main.orders'))


@main.route('/orders')
def orders():
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))

    all_orders = Order.query.filter_by(user_link=session['user_id']).all()
    return render_template('orders.html', orders=all_orders)


@main.route('/search', methods=['GET', 'POST'])
def search():
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))
    elif request.method == 'POST':
        search_product = request.form.get('search-product')
        products = Product.query.filter(Product.product_name.ilike(f'%{search_product}%')).all()
        return render_template('search.html', products=products,
                               cart=Cart.query.filter_by(user_link=session['user_id']).all())

    return render_template('search.html')


@main.route('/contact-us', methods=['GET', 'POST'])
def contact_us():
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))
    if request.method == 'POST':
        flash('Your message has been sent. Thank you', 'success')
    return render_template('contact.html')


@main.route('/about-us')
def about_us():
    if 'user_id' not in session:
        flash('You need to be logged in.', 'danger')
        return redirect(url_for('auth.login'))
    return render_template('about.html')

app/templates/admin.html
{% extends "base.html" %} {% block title %}Admin Panel{% endblock %} {% block
body %}

<table class="table table-light text-center">
  <thead>
    <tr>
      <th scope="col">Customers</th>
      <th scope="col">Shop Products</th>
      <th scope="col">Add Shop Product</th>
      <th scope="col">View Orders</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><a href="{{url_for('admin.app_users')}}">Customers</a></td>
      <td><a href="{{url_for('admin.shop_products')}}">Show Products</a></td>
      <td><a href="{{url_for('admin.add_product')}}">Add New Product</a></td>
      <td><a href="{{url_for('admin.view_orders')}}">View Orders</a></td>
    </tr>
  </tbody>
</table>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
      crossorigin="anonymous"
    ></script>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
    />

    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/index.css')}}"
    />

    <title>Electronic Store | {% block title %} {% endblock %}</title>
  </head>
  <body>
    <header class="p-3 bg-dark text-white shadow-sm">
      <div class="container">
        <div
          class="d-flex flex-wrap align-items-center justify-content-between"
        >
          <ul class="nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                href="{{url_for('main.home')}}"
                class="nav-link px-3 text-white"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a
                href="{{url_for('main.about_us')}}"
                class="nav-link px-3 text-white"
                >About Us</a
              >
            </li>
            {% if session['user_id'] == 1 %}
            <li class="nav-item">
              <a
                href="{{url_for('admin.admin_panel')}}"
                class="nav-link px-3 text-white"
                >Admin Panel</a
              >
            </li>
            {% endif %}
            <li class="nav-item">
              <a
                href="{{url_for('main.contact_us')}}"
                class="nav-link px-3 text-white"
                >Contact Us</a
              >
            </li>
          </ul>

          <form
            class="d-flex align-items-center me-4"
            role="search"
            action="{{url_for('main.search')}}"
            method="POST"
          >
            <input
              type="search"
              class="form-control form-control-dark text-bg-dark me-2"
              placeholder="Search..."
              aria-label="Search"
              name="search-product"
            />
            <button type="submit" class="btn btn-outline-light">Search</button>
          </form>

          <ul class="nav me-4">
            <li class="nav-item">
              <a
                href="{{url_for('main.view_cart')}}"
                class="nav-link text-white"
              >
                <i class="bi bi-cart-fill"></i> Cart
              </a>
            </li>
          </ul>

          <div class="dropdown">
            <button
              class="btn btn-outline-light dropdown-toggle"
              type="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              Account
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              {% if 'user_id' in session %}
              <li>
                <a
                  class="dropdown-item"
                  href="{{url_for('auth.profile', user_id=session['user_id'])}}"
                >
                  Profile <i class="bi bi-person-circle"></i>
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{{url_for('auth.logout')}}">
                  Log Out <i class="bi bi-box-arrow-in-right"></i>
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{{url_for('main.orders')}}">
                  Orders <i class="bi bi-truck"></i>
                </a>
              </li>
              {% else %}
              <li>
                <a class="dropdown-item" href="{{url_for('auth.login')}}">
                  Log In <i class="bi bi-box-arrow-in-left"></i>
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{{url_for('auth.register')}}">
                  Sign Up
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </header>

    {% for message in get_flashed_messages() %}

    <div
      class="alert alert-success alert-dismissible fade show"
      role="alert"
      style="margin-top: 5px"
    >
      <strong>{{ message }}</strong>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endfor %} {% block body %} {% endblock %}

    <div class="container">
      <footer
        class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top"
      >
        <p class="col-md-4 mb-0 text-body-secondary">© 2025 Electronic Store</p>
        <a
          href="/"
          class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none"
          aria-label="Bootstrap"
        >
          Electronic Store
        </a>
        <ul class="nav col-md-4 justify-content-end">
          <li class="nav-item">
            <a
              href="{{url_for('main.home')}}"
              class="nav-link px-2 text-body-secondary"
              >Home</a
            >
          </li>
          <li class="nav-item">
            <a
              href="{{url_for('main.about_us')}}"
              class="nav-link px-2 text-body-secondary"
              >About Us</a
            >
          </li>
          <li class="nav-item">
            <a
              href="{{url_for('main.contact_us')}}"
              class="nav-link px-2 text-body-secondary"
              >Contact Us</a
            >
          </li>
        </ul>
      </footer>
    </div>
  </body>
</html>

app/templates/checkout.html
{% extends 'base.html' %}
{% block title %}Checkout{% endblock %}

{% block body %}
<div class="container my-5">
  <div class="row g-5">
    
    <!-- Shipping Information -->
    <div class="col-md-7">
      <h3 class="mb-4">Shipping Information</h3>
      <form method="POST" action="">
        <div class="row mb-3">
          <div class="col-md-6">
            <label for="firstName" class="form-label">First Name</label>
            <input type="text" class="form-control" id="firstName" name="first-name" required>
          </div>
          <div class="col-md-6">
            <label for="lastName" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="lastName" name="last-name" required>
          </div>
        </div>
        <div class="mb-3">
          <label for="address" class="form-label">Address</label>
          <input type="textarea" class="form-control" id="address" name="address" required>
        </div>
        <div class="mb-3">
          <label for="city" class="form-label">City</label>
          <input type="text" class="form-control" id="city" name="city" required>
        </div>
        <div class="row mb-3">
          <div class="col-md-6">
            <label for="state" class="form-label">State</label>
            <input type="text" class="form-control" id="state" name="state" required>
          </div>
          <div class="col-md-6">
            <label for="pin" class="form-label">Pin Code</label>
            <input type="number" class="form-control" id="pin" name="pin" required>
          </div>
        </div>
        <div class="mb-3">
          <label for="phone" class="form-label">Phone Number</label>
          <input type="number" class="form-control" id="phone" name="phone-number" required>
        </div>
      </form>
    </div>

    <!-- Order Summary -->
    <div class="col-md-5">
      <h3 class="mb-4">Order Summary</h3>
      <ul class="list-group mb-3">
        {% for item in cart %}
        <li class="list-group-item d-flex justify-content-between lh-sm">
          <div>
            <h6 class="my-0">{{ item.product.product_name }}</h6>
            <small class="text-muted">Qty: {{ item.quantity }}</small>
          </div>
          <span class="text-muted">₹{{ item.product.discounted_price * item.quantity }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between">
          <strong>Total (INR)</strong>
          <strong>₹{{ total_amount }}</strong>
        </li>
      </ul>

      <a class="btn btn-primary w-100" href='{{url_for("main.order_confirm")}}'>Place Order</a>
    </div>

  </div>
</div>
{% endblock %}

app/templates/contact.html
{% extends 'base.html' %} {% block title %}Contact Us{% endblock %} {% block
body %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="text-center mb-5">
        <h2 class="fw-bold">Get in Touch</h2>
        <p class="text-muted">
          Have a question or feedback? We'd love to hear from you!
        </p>
      </div>

      <div class="card shadow border-0">
        <div class="card-body p-4">
          <form method="POST" action="{{url_for('main.contact_us')}}">
            <div class="mb-3">
              <label for="name" class="form-label">Your Name</label>
              <input
                type="text"
                class="form-control"
                id="name"
                name="name"
                placeholder="Enter your name"
                required
              />
            </div>

            <div class="mb-3">
              <label for="email" class="form-label">Email address</label>
              <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="you@example.com"
                required
              />
            </div>

            <div class="mb-3">
              <label for="subject" class="form-label">Subject</label>
              <input
                type="text"
                class="form-control"
                id="subject"
                name="subject"
                placeholder="Subject of your message"
              />
            </div>

            <div class="mb-3">
              <label for="message" class="form-label">Message</label>
              <textarea
                class="form-control"
                id="message"
                name="message"
                rows="5"
                placeholder="Write your message here..."
                required
              ></textarea>
            </div>

            <div class="d-grid">
              <button type="submit" class="btn btn-primary btn-lg">
                <i class="bi bi-send-fill me-2"></i>Send Message
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %} {% block title %} Home {% endblock %} {% block body %}
<div class="container col-xl-8">
  <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
    <div class="col-10 col-sm-8 col-lg-6">
      <img
        src="{{url_for('static', filename='images/noice watch(1)black.jpg')}}"
        class="d-block mx-lg-auto img-fluid"
        alt="banner-image"
        width="500"
        height="500"
        loading="lazy"
      />
    </div>
    <div class="col-lg-6">
      <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">
        Upgrade Your Tech Game
      </h1>
      <p class="lead">
        Explore the latest electronics — from smartphones to smart TVs, we have
        it all at unbeatable prices.
      </p>
    </div>
  </div>
</div>

<!-- Features Section -->
<div class="container" id="featured-3">
  <div class="row g-4 py-3 row-cols-1 row-cols-lg-3">
    <div class="feature col bg-body-tertiary">
      <div
        class="feature-icon d-inline-flex align-items-center justify-content-center fs-2 mb-3"
      >
        <i class="bi bi-truck"></i>
      </div>
      <h3 class="fs-2 text-body-emphasis">Fast & Free Shipping</h3>
      <p>On orders above ₹999 to most pin codes.</p>
    </div>
    <div class="feature col bg-body-tertiary">
      <div
        class="feature-icon d-inline-flex align-items-center justify-content-center fs-2 mb-3"
      >
        <i class="bi bi-credit-card"></i>
      </div>
      <h3 class="fs-2 text-body-emphasis">Secure Payments</h3>
      <p>Razorpay, UPI, Cards, EMI — all protected.</p>
    </div>
    <div class="feature col bg-body-tertiary">
      <div
        class="feature-icon d-inline-flex align-items-center justify-content-center fs-2 mb-3"
      >
        <i class="bi bi-star"></i>
      </div>
      <h3 class="fs-2 text-body-emphasis">Top Rated Brands</h3>
      <p>Apple, Samsung, Sony, Lenovo & more.</p>
    </div>
  </div>
</div>

<section class="py-5">
  <div class="container">
    <h2 class="fw-bold text-center mb-4">Products</h2>
    <p class="text-muted text-center mb-5">Top deals you don't want to miss!</p>

    <div class="row g-4">
      {% for product in products%}
      <div class="col-md-4">
        <div class="card h-100 border-0 shadow-lg position-relative">
          <span class="badge bg-danger position-absolute top-0 end-0 m-2"
            >{{product.discount_percentage}}% OFF</span
          >

          <img
            src="{{product.product_image}}"
            class="card-img-top"
            alt="Product 1"
          />
          <div class="card-body text-center">
            <h5 class="card-title">{{product.product_name}}</h5>
            <div class="mb-2">
              <span class="text-muted text-decoration-line-through"
                >₹ {{product.mrp}}</span
              >
              <span class="text-primary fw-bold ms-2"
                >₹ {{product.discounted_price}}</span
              >
            </div>
            <a
              href="{{url_for('main.add_to_cart', product_id=product.id)}}"
              class="btn btn-outline-primary mt-2"
              >Add To Cart</a
            >
          </div>
        </div>
      </div>
      {%endfor%}
    </div>
  </div>
</section>

{% endblock %}

app/templates/search.html
{% extends 'base.html' %} {% block title %} Search {% endblock %} {% block body
%} {% if products | length < 1 %}
<h3 style="color: white">No items match your search query</h3>
{% else %}
<div class="row g-4">
  {% for product in products %}
  <div class="col-md-4">
    <div class="card h-100 border-0 shadow-lg position-relative">
      <span class="badge bg-danger position-absolute top-0 end-0 m-2"
        >{{product.discount_percentage}}% OFF</span
      >

      <img
        src="{{product.product_image}}"
        class="card-img-top"
        alt="Product 1"
      />
      <div class="card-body text-center">
        <h5 class="card-title">{{product.product_name}}</h5>
        <div class="mb-2">
          <span class="text-muted text-decoration-line-through"
            >₹ {{product.mrp}}</span
          >
          <span class="text-primary fw-bold ms-2"
            >₹ {{product.discounted_price}}</span
          >
        </div>
        <a
          href="{{url_for('main.add_to_cart', product_id=product.id)}}"
          class="btn btn-outline-primary mt-2"
          >Add To Cart</a
        >
      </div>
    </div>
  </div>
  {%endfor%}
</div>
{% endif %} {% endblock %}

app/templates/shop-products.html
{% extends "base.html" %} {% block title %}Shop Items{% endblock %} {% block
body %} {% if products | length < 1 %}
<h3>No Shop Items</h3>
{% else %}
<table class="table table-secondary table-hover text-center">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Date Added</th>
      <th scope="col">Product Name</th>
      <th scope="col">MRP</th>
      <th scope="col">Discounted Price</th>
      <th scope="col">Discount</th>
      <th scope="col">Stock Amount</th>
      <th scope="col">Product Image</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr>
      <th scope="col">{{product.id}}</th>
      <td scope="col">{{product.date_added}}</td>
      <td scope="col">{{product.product_name}}</td>
      <td scope="col">{{product.mrp}}</td>
      <td scope="col">{{product.discounted_price}}</td>
      <td scope="col">{{product.discount_percentage}}</td>
      <td scope="col">{{product.in_stock}}</td>
      <td>
        <img
          src="{{ product.product_image }}"
          alt="{{product.product_name}}-img"
          style="height: 50px; width: 50px; border-radius: 2px"
        />
      </td>
      <td>
        <a href="{{url_for('admin.update_product', product_id=product.id)}}"
          >Update</a
        ><br />
        <a href="{{url_for('admin.delete_product', product_id=product.id)}}"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %} {% endblock %}